### ISSUE TITLE
Unable to install version 0.4.5

### ISSUE THREAD

**Issue by bigwhoopgames** [lmas/opensimplex#45]
I am unable to install version 0.4.5

pip install .\opensimplex-0.4.5.zip
Processing c:\users\derp\downloads\opensimplex-0.4.5.zip
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [27 lines of output]
      Traceback (most recent call last):
        File "C:\Users\Derp\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\Derp\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Derp\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Derp\AppData\Local\Temp\pip-build-env-xj4mpq9_\overlay\Lib\site-packages\setuptools\build_meta.py", line 341, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Derp\AppData\Local\Temp\pip-build-env-xj4mpq9_\overlay\Lib\site-packages\setuptools\build_meta.py", line 323, in _get_build_requires
          self.run_setup()
        File "C:\Users\Derp\AppData\Local\Temp\pip-build-env-xj4mpq9_\overlay\Lib\site-packages\setuptools\build_meta.py", line 488, in run_setup
          self).run_setup(setup_script=setup_script)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Derp\AppData\Local\Temp\pip-build-env-xj4mpq9_\overlay\Lib\site-packages\setuptools\build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 4, in <module>
        File "C:\Users\Derp\AppData\Local\Temp\pip-req-build-7enj910b\opensimplex\__init__.py", line 4, in <module>
          from .api import *
        File "C:\Users\Derp\AppData\Local\Temp\pip-req-build-7enj910b\opensimplex\api.py", line 1, in <module>
          from .constants import np
        File "C:\Users\Derp\AppData\Local\Temp\pip-req-build-7enj910b\opensimplex\constants.py", line 1, in <module>
          import numpy as np
      ModuleNotFoundError: No module named 'numpy'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

This is despite having numpy installed:

pip install numpy
Requirement already satisfied: numpy in c:\users\derp\appdata\local\programs\python\python311\lib\site-packages (1.25.1)

https://pypi.org/project/opensimplex/ lists the latest version as 0.4.4

Is 0.4.5 not official or has something gone wrong?

**Comment by lmas** [comment]
No idea what it's failing with that zip and numpy is just optional anyway.

I haven't uploaded 0.4.5 to pypi yet, had some issue with pypi back then and was already too busy in life.
I'll take a look at it again and try upload latest version later today.

**Comment by lmas** [comment]
Just pushed v0.4.5 to pypi so you should be able to install it normally with pip. Reopen/comment if you have any more problems.
